#!/usr/bin/env bash

if [ "$SUPERVISOR_PHP_USER" != "root" ] && [ "$SUPERVISOR_PHP_USER" != "sail" ]; then
    echo "You should set SUPERVISOR_PHP_USER to either 'sail' or 'root'."
    exit 1
fi

# Remove Vite hot file so Laravel uses built assets from manifest when dev server is not running.
# When you run `sail npm run dev`, Vite will recreate this file for HMR.
rm -f /var/www/html/public/hot

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

# Ensure Vite can write cache and temp files when running as sail in the container.
if [ -d /var/www/html/node_modules ]; then
    mkdir -p /var/www/html/node_modules/.vite-temp /var/www/html/node_modules/.vite
    chown -R sail:sail /var/www/html/node_modules/.vite-temp /var/www/html/node_modules/.vite
    chmod -R 777 /var/www/html/node_modules/.vite-temp /var/www/html/node_modules/.vite
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
        exec "$@"
    else
        exec gosu $WWWUSER "$@"
    fi
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
